### ISSUE TITLE
ondrej/php and ubuntu 23.04 lunar

### ISSUE THREAD

**Issue by rezabagheri** [genesisweb/valet-linux-plus#107] opened 2023-06-21 07:03 UTC
after upgrading Ubuntu to 23.04 lunar, we have this error:
the ppa(ondrej/php does not support ubuntu 23.04 lunar
Err:11 https://ppa.launchpadcontent.net/nginx/stable/ubuntu lunar Release
  404  Not Found [IP: 185.125.190.52 443]
Err:12 https://ppa.launchpadcontent.net/ondrej/php/ubuntu lunar Release
  404  Not Found [IP: 185.125.190.52 443]

also `valet secure` has not worked!
`➜ valet secure csp 
Restarting nginx...

The [csp.test] site has been secured with a fresh TLS certificate.
➜  valet secured csp

csp is not secured.`

**Comment by uttamrabadiya** [comment] 2023-06-23 15:01
@rezabagheri This is something odd! Could you please try with `localhost` domain instead of `test`? And also if you could specify your browser then I may can help in detail.

**Comment by rezabagheri** [comment] 2023-06-24 06:05
It is the same problem on all domains, including localhost, .test, etc.
Before upgrading from Ubuntu 22.10, to U until 23.04, there was no problem, I used brave, Firefox and Chrome browsers.

**Comment by SupianIDz** [comment] 2023-07-08 17:20
@rezabagheri I'm using Ubuntu 23.04 and I haven't had any issues, I think you should make sure `apt-transport-https` is installed.

**Comment by uttamrabadiya** [comment] 2024-06-13 05:29
@rezabagheri It seems the issue is resolved, I am closing this.

**Closed by uttamrabadiya** 2024-06-13 05:29 UTC
